table:
  name: shipment
  fields:
    - name: id
      type: int
      min: 1
      max: 1000000
    - name: name
      type: varchar(50)
      size: 50
    - name: country
      type: varchar(50)
      size: 50
      values: ["UK", "India", "Australia", "USA", "Germany", "France", "Finland"]
    - name: transaction_amount
      type: real
      min: 100
      max: 200000
    - name: transaction_quantity
      type: int
      min: 1
      max: 1000
    - name: product
      type: varchar(50)
      size: 50
      values: ["Shoes", "t-shirts", "pants", "sunglasses", "electorics", "software", "furniture"]
    - name: inserted_on
      type: timestamp
    - name: shipping_location
      type: varchar(50)
      size: 50
      values: ["UK", "India", "Australia", "USA", "Germany", "France", "Finland"]
    - name: updated_on
      type: timestamp
    - name: shipping_address
      type: varchar(100)
      size: 100

# Can be set as environment variables
connection:
  type: kafka # CONNECTION_TYPE
  bootstrapServers: # BOOTSTRAP_SERVERS
    - kafka:9092
  namespace: io.karthik.cepengine
  schemaRegistryUrl: http://schema-registry:8081 # SCHEMA_REGISTRY_URL

records: "100000" # RECORDS
frequency: 2 # FREQUENCY -> for ten records a second use 0.1

#docker run --rm \
#  --network sources \ # Network to join
#  -e FILE_LOCATION=/config/kafka.config.yml \ # Config file location
#  -v ${PWD}/config:/config \ # Config mount
#  --name data-generator-shipment-kafka \
#  flairbi/flair-data-generator